//! Port forwarding: local (`ssh -L`), remote (`ssh -R`) and dynamic/SOCKS5
//! (`ssh -D`).
//!
//! libssh2 is not thread-safe: a session and all channels opened on it must be
//! touched by exactly one thread. Each forward therefore owns a *dedicated*
//! SSH session and runs a single event-loop thread that accepts new
//! connections and pumps every open channel without blocking. Reusing the
//! shell session instead would either race with the terminal thread or
//! serialize terminal I/O behind tunnel traffic.
//!
//! A forward's lifetime is independent of any terminal tab: the point of a
//! forward is usually to let some *other* program (DB client, browser) reach a
//! service, which must keep working with no terminal open.

use crate::ssh::bridge::COPY_BUF_SIZE;
use crate::ssh::socks5::{
    success_reply, HandshakeProgress, SocksHandshake, REPLY_CONNECTION_REFUSED,
    REPLY_HOST_UNREACHABLE, REPLY_SUCCESS,
};
use serde::{Deserialize, Serialize};
use ssh2::{Channel, Session};
use std::collections::HashMap;
use std::io::{ErrorKind, Read, Write};
use std::net::{IpAddr, Ipv4Addr, Shutdown, SocketAddr, TcpListener, TcpStream, ToSocketAddrs};
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, MutexGuard};
use std::thread;
use std::time::{Duration, Instant};
use tauri::{AppHandle, Emitter};

pub const PORT_FORWARD_STATUS_EVENT: &str = "port-forward-status";
pub const PORT_FORWARD_PROGRESS_EVENT: &str = "port-forward-progress";

/// Poll interval while connections are actively transferring.
const ACTIVE_POLL_MS: u64 = 1;
/// Poll interval while the forward is only waiting for a new connection.
/// Costs at most this much accept latency, which is imperceptible, and keeps
/// an idle forward from burning a core.
const IDLE_POLL_MS: u64 = 20;
/// Per-direction buffer cap. Once this much data is queued we stop reading
/// from that side, so a slow peer applies backpressure instead of growing the
/// buffer without bound.
const MAX_PENDING_BYTES: usize = 512 * 1024;
/// Bound on a single channel-open round trip. The session is switched to
/// blocking mode for the open, so a hung open would otherwise stall every
/// other connection on this forward for the full operation timeout.
const CHANNEL_OPEN_TIMEOUT_MS: u32 = 10_000;
/// Bound on connecting to the local target of a remote (`-R`) forward.
const LOCAL_CONNECT_TIMEOUT: Duration = Duration::from_secs(5);
/// Cap on SOCKS handshakes in flight, so a port scanner cannot grow the list.
const MAX_PENDING_HANDSHAKES: usize = 64;
const KEEPALIVE_INTERVAL: Duration = Duration::from_secs(30);
/// `LIBSSH2_ERROR_EAGAIN`. On a non-blocking session this means "try again",
/// not "the connection died".
const LIBSSH2_ERROR_EAGAIN: i32 = -37;

fn is_would_block(error: &ssh2::Error) -> bool {
    matches!(error.code(), ssh2::ErrorCode::Session(LIBSSH2_ERROR_EAGAIN))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ForwardKind {
    /// `ssh -L`: we listen locally, the server reaches the destination.
    Local,
    /// `ssh -R`: the server listens, we reach the destination locally.
    Remote,
    /// `ssh -D`: we listen locally as a SOCKS5 proxy; the destination comes
    /// from each SOCKS request, so the server reaches a different host per
    /// connection.
    Dynamic,
}

/// One forwarding rule. `id` is generated by the frontend and stored with the
/// saved session, so it survives restarts and identifies the rule everywhere.
///
/// The address fields mean different things per kind — the frontend uses one
/// shape for all three, so they are deliberately generic:
///
/// | field         | Local                  | Remote                       | Dynamic          |
/// |---------------|------------------------|------------------------------|------------------|
/// | `local_host`  | address we bind        | host we connect to here      | address we bind  |
/// | `local_port`  | port we listen on      | port we connect to here      | SOCKS port       |
/// | `remote_host` | destination host       | address the server binds     | unused           |
/// | `remote_port` | destination port       | port the server listens on   | unused           |
#[derive(Debug, Clone)]
pub struct ForwardRuleSpec {
    pub id: String,
    pub kind: ForwardKind,
    pub local_host: String,
    pub local_port: u16,
    pub remote_host: String,
    pub remote_port: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ForwardState {
    Running,
    Stopped,
    Error,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PortForwardStatus {
    pub rule_id: String,
    pub saved_session_id: String,
    pub kind: ForwardKind,
    pub state: ForwardState,
    pub local_host: String,
    pub local_port: u16,
    pub remote_host: String,
    pub remote_port: u16,
    pub active_connections: u32,
    pub total_connections: u64,
    pub message: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PortForwardProgress {
    pub rule_id: String,
    pub line: String,
}

#[derive(Default)]
pub struct ForwardStats {
    active: AtomicU32,
    total: AtomicU64,
}

/// Where new tunneled connections come from. Local and dynamic forwards listen
/// on this machine; a remote forward has the SSH server listen on its behalf.
pub enum ForwardSource {
    LocalSocket(TcpListener),
    RemoteChannel(ssh2::Listener),
}

struct RunningForward {
    saved_session_id: String,
    spec: ForwardRuleSpec,
    stop: Arc<AtomicBool>,
    /// Set by the loop thread once its listener and session are released.
    /// `stop_forward` waits on this so restarting a rule cannot race the old
    /// thread and fail with "address already in use".
    done: Arc<AtomicBool>,
    stats: Arc<ForwardStats>,
}

pub struct PortForwardManager {
    forwards: Mutex<HashMap<String, RunningForward>>,
}

/// Everything one forward thread owns. Bundled so the thread signature stays
/// readable.
pub struct ForwardRuntime {
    pub session: Session,
    /// Kept alive only so the bastion tunnel carrying `session` stays open;
    /// dropping it closes the tunnel.
    pub bastion_session: Option<Session>,
    pub source: ForwardSource,
    pub spec: ForwardRuleSpec,
    pub saved_session_id: String,
    pub stop: Arc<AtomicBool>,
    pub done: Arc<AtomicBool>,
    pub stats: Arc<ForwardStats>,
    pub manager: Arc<PortForwardManager>,
    pub app: AppHandle,
}

impl PortForwardManager {
    pub fn new() -> Self {
        Self {
            forwards: Mutex::new(HashMap::new()),
        }
    }

    /// Locks the forward map, recovering from poisoning so one panic while
    /// holding the lock does not brick every subsequent command.
    fn lock_forwards(&self) -> MutexGuard<'_, HashMap<String, RunningForward>> {
        self.forwards.lock().unwrap_or_else(|e| e.into_inner())
    }

    pub fn is_running(&self, rule_id: &str) -> bool {
        self.lock_forwards().contains_key(rule_id)
    }

    /// Registers a started forward and returns its initial status. Fails if the
    /// rule is already running: two threads for one rule would fight over the
    /// same local port.
    ///
    /// The status is built here rather than read back afterwards, so a forward
    /// that dies immediately cannot make a successful start look like a failure.
    pub fn insert(
        &self,
        saved_session_id: String,
        spec: ForwardRuleSpec,
        stop: Arc<AtomicBool>,
        done: Arc<AtomicBool>,
        stats: Arc<ForwardStats>,
    ) -> Result<PortForwardStatus, String> {
        let mut guard = self.lock_forwards();
        if guard.contains_key(&spec.id) {
            return Err("This port forward is already running.".to_string());
        }
        let status = status_of(&spec, &saved_session_id, ForwardState::Running, &stats, None);
        guard.insert(
            spec.id.clone(),
            RunningForward {
                saved_session_id,
                spec,
                stop,
                done,
                stats,
            },
        );
        Ok(status)
    }

    /// Signals the forward to stop and removes it from the map. Returns the
    /// thread's `done` flag so the caller can wait for the port to be free.
    pub fn request_stop(&self, rule_id: &str) -> Option<Arc<AtomicBool>> {
        let removed = self.lock_forwards().remove(rule_id)?;
        removed.stop.store(true, Ordering::Relaxed);
        Some(removed.done)
    }

    /// Stops every forward belonging to one saved session (used by "stop all").
    pub fn request_stop_for_session(&self, saved_session_id: &str) -> Vec<Arc<AtomicBool>> {
        let mut guard = self.lock_forwards();
        let ids: Vec<String> = guard
            .iter()
            .filter(|(_, f)| f.saved_session_id == saved_session_id)
            .map(|(id, _)| id.clone())
            .collect();
        ids.into_iter()
            .filter_map(|id| guard.remove(&id))
            .map(|f| {
                f.stop.store(true, Ordering::Relaxed);
                f.done
            })
            .collect()
    }

    /// Removes the entry only if it still belongs to `stop`. A forward thread
    /// that dies while the user has already restarted the rule must not evict
    /// the *new* thread's entry.
    fn remove_if_owned(&self, rule_id: &str, stop: &Arc<AtomicBool>) {
        let mut guard = self.lock_forwards();
        let is_owner = guard
            .get(rule_id)
            .is_some_and(|f| Arc::ptr_eq(&f.stop, stop));
        if is_owner {
            guard.remove(rule_id);
        }
    }

    pub fn statuses(&self) -> Vec<PortForwardStatus> {
        self.lock_forwards()
            .values()
            .map(|f| {
                status_of(
                    &f.spec,
                    &f.saved_session_id,
                    ForwardState::Running,
                    &f.stats,
                    None,
                )
            })
            .collect()
    }
}

fn status_of(
    spec: &ForwardRuleSpec,
    saved_session_id: &str,
    state: ForwardState,
    stats: &ForwardStats,
    message: Option<String>,
) -> PortForwardStatus {
    PortForwardStatus {
        rule_id: spec.id.clone(),
        saved_session_id: saved_session_id.to_string(),
        kind: spec.kind,
        state,
        local_host: spec.local_host.clone(),
        local_port: spec.local_port,
        remote_host: spec.remote_host.clone(),
        remote_port: spec.remote_port,
        active_connections: stats.active.load(Ordering::Relaxed),
        total_connections: stats.total.load(Ordering::Relaxed),
        message,
    }
}

pub fn emit_status(app: &AppHandle, status: &PortForwardStatus) {
    let _ = app.emit(PORT_FORWARD_STATUS_EVENT, status);
}

pub fn emit_progress(app: &AppHandle, rule_id: &str, line: &str) {
    let _ = app.emit(
        PORT_FORWARD_PROGRESS_EVENT,
        PortForwardProgress {
            rule_id: rule_id.to_string(),
            line: line.to_string(),
        },
    );
}

/// Resolves the local bind address. Defaults to loopback: binding a tunnel to
/// `0.0.0.0` exposes an internal service to the whole network, so it must be
/// an explicit choice by the user, never a fallback.
pub fn resolve_bind_ip(local_host: &str) -> Result<IpAddr, String> {
    let host = local_host.trim();
    if host.is_empty() || host.eq_ignore_ascii_case("localhost") {
        return Ok(IpAddr::V4(Ipv4Addr::LOCALHOST));
    }
    host.parse::<IpAddr>()
        .map_err(|_| format!("Invalid local bind address: {}", local_host))
}

/// One tunneled TCP connection. Both directions are buffered so neither side
/// can block the shared event loop: we read only while the outbound buffer has
/// room, and write only what the non-blocking peer accepts right now.
struct ForwardConnection {
    channel: Channel,
    stream: TcpStream,
    /// Read from the local socket, not yet accepted by the SSH channel.
    to_channel: Vec<u8>,
    /// Read from the SSH channel, not yet accepted by the local socket.
    to_stream: Vec<u8>,
    local_eof: bool,
    remote_eof: bool,
    sent_eof: bool,
    shutdown_write: bool,
}

impl ForwardConnection {
    fn new(channel: Channel, stream: TcpStream) -> Self {
        Self {
            channel,
            stream,
            to_channel: Vec::new(),
            to_stream: Vec::new(),
            local_eof: false,
            remote_eof: false,
            sent_eof: false,
            shutdown_write: false,
        }
    }

    /// Moves whatever is ready in either direction. Returns whether any byte
    /// moved (so the loop knows not to sleep), or `Err` if the connection is
    /// dead and must be dropped.
    fn pump(&mut self, buf: &mut [u8]) -> Result<bool, ()> {
        let mut progressed = false;

        // local socket → SSH channel
        if !self.local_eof && self.to_channel.len() < MAX_PENDING_BYTES {
            match self.stream.read(buf) {
                Ok(0) => self.local_eof = true,
                Ok(n) => {
                    self.to_channel.extend_from_slice(&buf[..n]);
                    progressed = true;
                }
                Err(e) if e.kind() == ErrorKind::WouldBlock => {}
                Err(_) => return Err(()),
            }
        }
        progressed |= drain_pending(&mut self.channel, &mut self.to_channel)?;
        if self.local_eof && self.to_channel.is_empty() && !self.sent_eof {
            // Half-close: the other side may still have a reply to send
            // (this is how "shutdown then read" clients work).
            let _ = self.channel.send_eof();
            self.sent_eof = true;
        }

        // SSH channel → local socket
        if !self.remote_eof && self.to_stream.len() < MAX_PENDING_BYTES {
            match self.channel.read(buf) {
                // On a non-blocking channel Ok(0) usually means "no data";
                // only eof() distinguishes a real close.
                Ok(0) => {
                    if self.channel.eof() {
                        self.remote_eof = true;
                    }
                }
                Ok(n) => {
                    self.to_stream.extend_from_slice(&buf[..n]);
                    progressed = true;
                }
                Err(e) if e.kind() == ErrorKind::WouldBlock => {}
                Err(_) => return Err(()),
            }
        }
        progressed |= drain_pending(&mut self.stream, &mut self.to_stream)?;
        if self.remote_eof && self.to_stream.is_empty() && !self.shutdown_write {
            let _ = self.stream.shutdown(Shutdown::Write);
            self.shutdown_write = true;
        }

        Ok(progressed)
    }

    fn is_finished(&self) -> bool {
        self.local_eof && self.remote_eof && self.to_channel.is_empty() && self.to_stream.is_empty()
    }

    fn close(&mut self) {
        let _ = self.channel.close();
        let _ = self.stream.shutdown(Shutdown::Both);
    }
}

/// Writes as much of `pending` as the non-blocking writer accepts right now.
/// A partial write is normal here; the remainder stays queued for the next tick.
fn drain_pending<W: Write>(dst: &mut W, pending: &mut Vec<u8>) -> Result<bool, ()> {
    let mut progressed = false;
    while !pending.is_empty() {
        match dst.write(pending) {
            Ok(0) => return Err(()),
            Ok(n) => {
                pending.drain(..n);
                progressed = true;
            }
            Err(e) if e.kind() == ErrorKind::WouldBlock => break,
            Err(_) => return Err(()),
        }
    }
    Ok(progressed)
}

/// Opens a tunnel channel in blocking mode. The loop otherwise runs the
/// session non-blocking, where a channel open would return EAGAIN and need a
/// hand-rolled retry loop for no benefit — the open is a single fast round
/// trip, bounded by `CHANNEL_OPEN_TIMEOUT_MS`.
fn open_tunnel_channel(session: &Session, host: &str, port: u16) -> Result<Channel, ssh2::Error> {
    session.set_blocking(true);
    let result = session.channel_direct_tcpip(host, port, None);
    session.set_blocking(false);
    result
}

/// Connects to the local destination of a remote (`-R`) forward. Bounded so a
/// firewalled local address cannot stall the whole forward.
fn connect_local_target(host: &str, port: u16) -> std::io::Result<TcpStream> {
    let mut last_error = std::io::Error::new(
        ErrorKind::AddrNotAvailable,
        format!("Could not resolve {}:{}", host, port),
    );
    for address in (host, port).to_socket_addrs()? {
        match TcpStream::connect_timeout(&address, LOCAL_CONNECT_TIMEOUT) {
            Ok(stream) => return Ok(stream),
            Err(e) => last_error = e,
        }
    }
    Err(last_error)
}

pub fn spawn_forward_thread(runtime: ForwardRuntime) {
    thread::spawn(move || run_forward_loop(runtime));
}

fn run_forward_loop(runtime: ForwardRuntime) {
    let ForwardRuntime {
        session,
        bastion_session,
        mut source,
        spec,
        saved_session_id,
        stop,
        done,
        stats,
        manager,
        app,
    } = runtime;

    session.set_blocking(false);
    session.set_keepalive(true, KEEPALIVE_INTERVAL.as_secs() as u32);
    session.set_timeout(CHANNEL_OPEN_TIMEOUT_MS);

    let mut connections: Vec<ForwardConnection> = Vec::new();
    let mut handshakes: Vec<SocksHandshake> = Vec::new();
    let mut buf = vec![0u8; COPY_BUF_SIZE];
    let mut last_keepalive = Instant::now();
    let mut last_reported_active = 0u32;
    let mut failure: Option<String> = None;

    while !stop.load(Ordering::Relaxed) {
        let mut progressed = false;

        match accept_next(&mut source, &session, &spec, &app, handshakes.len()) {
            Ok(Some(Accepted::Connection(connection))) => {
                progressed = true;
                stats.total.fetch_add(1, Ordering::Relaxed);
                connections.push(connection);
            }
            Ok(Some(Accepted::Handshake(handshake))) => {
                progressed = true;
                handshakes.push(handshake);
            }
            Ok(None) => {}
            Err(message) => {
                failure = Some(message);
                break;
            }
        }

        // SOCKS5 handshakes in flight: each tick moves them along, and a
        // finished one turns into a tunneled connection.
        let mut i = 0;
        while i < handshakes.len() {
            match handshakes[i].progress() {
                HandshakeProgress::Pending => i += 1,
                HandshakeProgress::Failed(reason) => {
                    emit_progress(&app, &spec.id, reason);
                    handshakes.swap_remove(i);
                }
                HandshakeProgress::Connect { host, port } => {
                    progressed = true;
                    let mut handshake = handshakes.swap_remove(i);
                    match open_tunnel_channel(&session, &host, port) {
                        Ok(channel) => {
                            let buffered = handshake.take_buffered_input();
                            let mut connection = ForwardConnection::new(channel, handshake.stream);
                            // The CONNECT reply rides the normal outbound
                            // buffer, so there is no separate write path.
                            connection
                                .to_stream
                                .extend_from_slice(&success_reply(REPLY_SUCCESS));
                            // Some clients send the request body immediately
                            // after CONNECT without waiting for the reply.
                            connection.to_channel.extend_from_slice(&buffered);
                            stats.total.fetch_add(1, Ordering::Relaxed);
                            connections.push(connection);
                        }
                        Err(e) => {
                            emit_progress(
                                &app,
                                &spec.id,
                                &format!("SOCKS: could not reach {}:{} — {}", host, port, e),
                            );
                            handshake.fail_with(if is_would_block(&e) {
                                REPLY_HOST_UNREACHABLE
                            } else {
                                REPLY_CONNECTION_REFUSED
                            });
                        }
                    }
                }
            }
        }

        let mut i = 0;
        while i < connections.len() {
            match connections[i].pump(&mut buf) {
                Ok(moved) => {
                    progressed |= moved;
                    if connections[i].is_finished() {
                        connections.swap_remove(i).close();
                        continue;
                    }
                    i += 1;
                }
                Err(()) => connections.swap_remove(i).close(),
            }
        }

        let active = connections.len() as u32;
        if active != last_reported_active {
            last_reported_active = active;
            stats.active.store(active, Ordering::Relaxed);
            emit_status(
                &app,
                &status_of(&spec, &saved_session_id, ForwardState::Running, &stats, None),
            );
        }

        if last_keepalive.elapsed() >= KEEPALIVE_INTERVAL {
            // A forward can sit idle for hours; without keepalives the server
            // or an intermediate firewall silently drops the session and the
            // next connection fails for no visible reason.
            match session.keepalive_send() {
                Ok(_) => last_keepalive = Instant::now(),
                // Leave `last_keepalive` alone so the send is retried next tick.
                Err(e) if is_would_block(&e) => {}
                Err(e) => {
                    failure = Some(format!("SSH connection lost: {}", e));
                    break;
                }
            }
        }

        if !progressed {
            let idle_ms = if connections.is_empty() && handshakes.is_empty() {
                IDLE_POLL_MS
            } else {
                ACTIVE_POLL_MS
            };
            thread::sleep(Duration::from_millis(idle_ms));
        }
    }

    for mut connection in connections {
        connection.close();
    }
    drop(handshakes);
    drop(source);
    // Back to blocking so the disconnect handshake in `drop` completes instead
    // of bailing out with EAGAIN.
    session.set_blocking(true);
    drop(session);
    drop(bastion_session);

    stats.active.store(0, Ordering::Relaxed);
    manager.remove_if_owned(&spec.id, &stop);
    let state = if failure.is_some() {
        ForwardState::Error
    } else {
        ForwardState::Stopped
    };
    emit_status(
        &app,
        &status_of(&spec, &saved_session_id, state, &stats, failure),
    );
    done.store(true, Ordering::Release);
}

enum Accepted {
    Connection(ForwardConnection),
    Handshake(SocksHandshake),
}

/// Takes at most one new connection per tick. `Err` means the listener itself
/// died and the forward cannot continue; a destination that merely refused the
/// connection is reported through the activity log and the forward stays up —
/// the service may be restarting.
fn accept_next(
    source: &mut ForwardSource,
    session: &Session,
    spec: &ForwardRuleSpec,
    app: &AppHandle,
    pending_handshakes: usize,
) -> Result<Option<Accepted>, String> {
    match source {
        ForwardSource::LocalSocket(listener) => {
            let (stream, peer) = match listener.accept() {
                Ok(accepted) => accepted,
                Err(e) if e.kind() == ErrorKind::WouldBlock => return Ok(None),
                Err(e) => return Err(format!("Local listener failed: {}", e)),
            };
            let _ = stream.set_nodelay(true);
            if let Err(e) = stream.set_nonblocking(true) {
                emit_progress(app, &spec.id, &format!("Dropped {}: {}", peer, e));
                return Ok(None);
            }

            if spec.kind == ForwardKind::Dynamic {
                if pending_handshakes >= MAX_PENDING_HANDSHAKES {
                    emit_progress(
                        app,
                        &spec.id,
                        "Too many SOCKS handshakes in flight; dropped a connection.",
                    );
                    let _ = stream.shutdown(Shutdown::Both);
                    return Ok(None);
                }
                return Ok(Some(Accepted::Handshake(SocksHandshake::new(stream))));
            }

            match open_tunnel_channel(session, &spec.remote_host, spec.remote_port) {
                Ok(channel) => Ok(Some(Accepted::Connection(ForwardConnection::new(
                    channel, stream,
                )))),
                Err(e) => {
                    emit_progress(
                        app,
                        &spec.id,
                        &format!(
                            "Could not open tunnel to {}:{} — {}",
                            spec.remote_host, spec.remote_port, e
                        ),
                    );
                    let _ = stream.shutdown(Shutdown::Both);
                    Ok(None)
                }
            }
        }
        ForwardSource::RemoteChannel(listener) => {
            let channel = match listener.accept() {
                Ok(channel) => channel,
                Err(e) if is_would_block(&e) => return Ok(None),
                Err(e) => return Err(format!("Server-side listener failed: {}", e)),
            };
            match connect_local_target(&spec.local_host, spec.local_port) {
                Ok(stream) => {
                    let _ = stream.set_nodelay(true);
                    if let Err(e) = stream.set_nonblocking(true) {
                        emit_progress(app, &spec.id, &format!("Dropped a connection: {}", e));
                        return Ok(None);
                    }
                    Ok(Some(Accepted::Connection(ForwardConnection::new(
                        channel, stream,
                    ))))
                }
                Err(e) => {
                    let mut channel = channel;
                    emit_progress(
                        app,
                        &spec.id,
                        &format!(
                            "Could not reach local {}:{} — {}",
                            spec.local_host, spec.local_port, e
                        ),
                    );
                    let _ = channel.close();
                    Ok(None)
                }
            }
        }
    }
}

/// Binds the local listener for local/dynamic forwards. Called before the SSH
/// handshake: a port conflict is by far the most common failure and costs
/// nothing to detect, while a handshake takes seconds.
pub fn bind_local_listener(spec: &ForwardRuleSpec) -> Result<TcpListener, String> {
    let ip = resolve_bind_ip(&spec.local_host)?;
    let addr = SocketAddr::new(ip, spec.local_port);
    let listener = TcpListener::bind(addr).map_err(|e| match e.kind() {
        ErrorKind::AddrInUse => format!(
            "Local port {} is already in use. Choose another port or stop the program using it.",
            spec.local_port
        ),
        ErrorKind::PermissionDenied => format!(
            "No permission to bind local port {}. Ports below 1024 require elevated privileges.",
            spec.local_port
        ),
        _ => format!("Could not bind {}: {}", addr, e),
    })?;
    listener
        .set_nonblocking(true)
        .map_err(|e| format!("Could not configure local listener: {}", e))?;
    Ok(listener)
}

/// Asks the SSH server to listen on our behalf (`ssh -R`). Returns the port the
/// server actually bound, which is the only way to learn it when 0 was
/// requested.
pub fn listen_on_server(
    session: &Session,
    spec: &ForwardRuleSpec,
) -> Result<(ssh2::Listener, u16), String> {
    let bind_host = spec.remote_host.trim();
    // None lets the server apply its own policy (OpenSSH binds loopback unless
    // GatewayPorts is on), which is the safer default.
    let host = if bind_host.is_empty() {
        None
    } else {
        Some(bind_host)
    };
    session
        .channel_forward_listen(spec.remote_port, host, None)
        .map_err(|e| {
            format!(
                "The server refused to listen on port {}: {}. Remote forwarding needs AllowTcpForwarding \
                 enabled, a free port, and GatewayPorts for a non-loopback bind address.",
                spec.remote_port, e
            )
        })
}
